### ISSUE TITLE
Error while loading shared libraries: cygboost_serialization-1_66.dll // ImportError: No such file or directory

### ISSUE THREAD

**Issue by gottfriedmrs** [cyang-kth/fmm#105]
Dear Can,

I have some troubles to get started with your FMM project. I am working on W10 with a clean install of Cygwin and I have followed your tuto for Windows users.

After building, installing and updating environment variables I try to run fmm in the /build folder, and I get the following error

```
xxxx@xxxx ~/fmm/build
$ fmm
C:/cygwin64/home/XXXXXX/fmm/build/fmm.exe: error while loading shared libraries: cygboost_serialization-1_66.dll: cannot open shared object file: No such file or directory
```

Where can I get this missing dll ?

On the other hand, when I try to import fmm through python (2.7) I get:

```
Python 2.7.18 (default, May 23 2020, 12:02:55)
[GCC 9.3.0] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fmm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fmm.py", line 17, in <module>
    _fmm = swig_import_helper()
  File "fmm.py", line 16, in swig_import_helper
    return importlib.import_module('_fmm')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No such file or directory
```

Here some elements that could be useful to solve this issue:
_fmm.dll dependencies (I see cygboost_serialization-1_66.dll as an output of `ldd _fmm.dll` in #71 but not in mine)

```

$ ldd _fmm.dll
ntdll.dll => /cygdrive/c/WINDOWS/SYSTEM32/ntdll.dll (0x7ffb1f3a0000)
KERNEL32.DLL => /cygdrive/c/WINDOWS/System32/KERNEL32.DLL (0x7ffb1cad0000)
KERNELBASE.dll => /cygdrive/c/WINDOWS/System32/KERNELBASE.dll (0x7ffb1b540000)
SYSFER.DLL => /cygdrive/c/WINDOWS/System32/SYSFER.DLL (0x5e7a0000)
_fmm.dll => /home/XXXXXX/fmm/build/python/_fmm.dll (0x45b1d0000)
cygwin1.dll => /usr/bin/cygwin1.dll (0x180040000)
cyggcc_s-seh-1.dll => /usr/bin/cyggcc_s-seh-1.dll (0x3f58b0000)
cygstdc++-6.dll => /usr/bin/cygstdc++-6.dll (0x3f0c90000)
libpython2.7.dll => /usr/bin/libpython2.7.dll (0x3efe20000)
cygpyfmmlib.dll => /home/XXXXXX/fmm/build/cygpyfmmlib.dll (0x57a300000)
cyggomp-1.dll => /usr/bin/cyggomp-1.dll (0x5f6ec0000)
```

added in ~/.bash_profile:

```
export PATH=/home/XXXXX/fmm/build:$PATH
export PYTHONPATH=/home/XXXXX/fmm/build/python:$PYTHONPATH
```
cmake call:
```
$ cmake .. -DPYTHON_INCLUDE_DIR=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")  -DPYTHON_LIBRARY=$(python -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))"
```
that is to say
```
cmake .. -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib
```

Is there any chance that I miss something during the installation ? Thanks in advance

**Comment by cyang-kth** [comment]
When you run `cmake ..`, you should be able to see the location of boost serialization:

https://ci.appveyor.com/project/cyang-kth/fmm#L3048

```
-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   serialization
-- Boost headers found at /usr/include
-- Boost library found at /usr/lib/libboost_serialization.dll.a
-- Boost library version 1_66
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
```

Did you run every command in the cygwin terminal instead of the windows cmd terminal?

**Comment by gottfriedmrs** [comment]
Thanks for your fast answer !

I run every command **in the cygwin terminal**. I try another DPYTHON_LIBRARY binding and got:

```
$ cmake .. -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib/python2.7:/usr/lib/python2.7/site-packages
-- CMAKE version 3.17.3
-- Set CMP0074 state to NEW
-- Set CMP0086 state to NEW
-- Set CMP0078 state to NEW
-- OSMium found at third_party/libosmium/include;/usr/include;third_party/protozero/include
-- OSMium library found at /usr/lib/libz.dll.a;/usr/lib/libexpat.dll.a;/usr/lib/libbz2.dll.a
-- GDAL headers found at /usr/include
-- GDAL library found at /usr/lib/libgdal.dll.a
-- Boost headers found at /usr/include
-- Boost library found at /usr/lib/libboost_serialization.dll.a
-- Boost library version 1_66
-- OpenMP_HEADERS found at
-- OpenMP_CXX_LIBRARIES found at /usr/lib/gcc/x86_64-pc-cygwin/9.3.0/libgomp.dll.a
-- Swig version is 3.0.12
-- Found PythonLibs: /usr/lib/python2.7:/usr/lib/python2.7/site-packages (found suitable version "2.7.18", minimum required is "2.7")
-- Python header found at /usr/include/python2.7
-- Python library found at /usr/lib/python2.7:/usr/lib/python2.7/site-packages
-- Using swig add library
-- Configuring done
-- Generating done
-- Build files have been written to: /home/GM263174/fmm/build

```

**Comment by gottfriedmrs** [comment]
Thanks for your fast answer !

I run every command in the cygwin terminal. I try another DPYTHON_LIBRARY binding and got:
```

$ cmake .. -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib/python2.7:/usr/lib/python2.7/site-packages
-- CMAKE version 3.17.3
-- Set CMP0074 state to NEW
-- Set CMP0086 state to NEW
-- Set CMP0078 state to NEW
-- OSMium found at third_party/libosmium/include;/usr/include;third_party/protozero/include
-- OSMium library found at /usr/lib/libz.dll.a;/usr/lib/libexpat.dll.a;/usr/lib/libbz2.dll.a
-- GDAL headers found at /usr/include
-- GDAL library found at /usr/lib/libgdal.dll.a
-- Boost headers found at /usr/include
-- Boost library found at /usr/lib/libboost_serialization.dll.a
-- Boost library version 1_66
-- OpenMP_HEADERS found at
-- OpenMP_CXX_LIBRARIES found at /usr/lib/gcc/x86_64-pc-cygwin/9.3.0/libgomp.dll.a
-- Swig version is 3.0.12
-- Found PythonLibs: /usr/lib/python2.7:/usr/lib/python2.7/site-packages (found suitable version "2.7.18", minimum required is "2.7")
-- Python header found at /usr/include/python2.7
-- Python library found at /usr/lib/python2.7:/usr/lib/python2.7/site-packages
-- Using swig add library
-- Configuring done
-- Generating done
-- Build files have been written to: /home/XXXXXX/fmm/build

```

**Comment by cyang-kth** [comment]
Can you try with 
```
cygcheck fmm.exe
```

**Comment by gottfriedmrs** [comment]
```
XXXX@XXXXX ~
$ cygcheck fmm.exe
Found: C:\cygwin64\home\GM263174\fmm\build\fmm.exe
Found: C:\cygwin64\usr\local\bin\fmm.exe
C:\cygwin64\home\GM263174\fmm\build\fmm.exe
  C:\cygwin64\bin\cygwin1.dll
    C:\WINDOWS\system32\KERNEL32.dll
      C:\Program Files\MiKTeX 2.9\miktex\bin\x64\api-ms-win-core-rtlsupport-l1-1-0.dll
      C:\WINDOWS\system32\ntdll.dll
      C:\WINDOWS\system32\KERNELBASE.dll
      C:\Program Files\MiKTeX 2.9\miktex\bin\x64\api-ms-win-core-processthreads-l1-1-0.dll
      C:\Program Files\MiKTeX 2.9\miktex\bin\x64\api-ms-win-core-processthreads-l1-1-1.dll
      C:\Program Files\MiKTeX 2.9\miktex\bin\x64\api-ms-win-core-heap-l1-1-0.dll
      C:\Program Files\MiKTeX 2.9\miktex\bin\x64\api-ms-win-core-memory-l1-1-0.dll
      C:\Program Files\MiKTeX 2.9\miktex\bin\x64\api-ms-win-core-handle-l1-1-0.dll
      C:\Program Files\MiKTeX 2.9\miktex\bin\x64\api-ms-win-core-synch-l1-1-0.dll
      C:\Program Files\MiKTeX 2.9\miktex\bin\x64\api-ms-win-core-synch-l1-2-0.dll
      C:\Program Files\MiKTeX 2.9\miktex\bin\x64\api-ms-win-core-file-l1-1-0.dll
      C:\Program Files\MiKTeX 2.9\miktex\bin\x64\api-ms-win-core-file-l1-2-0.dll
      C:\Program Files\MiKTeX 2.9\miktex\bin\x64\api-ms-win-core-namedpipe-l1-1-0.dll
      C:\Program Files\MiKTeX 2.9\miktex\bin\x64\api-ms-win-core-datetime-l1-1-0.dll
      C:\Program Files\MiKTeX 2.9\miktex\bin\x64\api-ms-win-core-sysinfo-l1-1-0.dll
      C:\Program Files\MiKTeX 2.9\miktex\bin\x64\api-ms-win-core-timezone-l1-1-0.dll
      C:\Program Files\MiKTeX 2.9\miktex\bin\x64\api-ms-win-core-localization-l1-2-0.dll
      C:\Program Files\MiKTeX 2.9\miktex\bin\x64\api-ms-win-core-processenvironment-l1-1-0.dll
      C:\Program Files\MiKTeX 2.9\miktex\bin\x64\api-ms-win-core-string-l1-1-0.dll
      C:\Program Files\MiKTeX 2.9\miktex\bin\x64\api-ms-win-core-debug-l1-1-0.dll
      C:\Program Files\MiKTeX 2.9\miktex\bin\x64\api-ms-win-core-errorhandling-l1-1-0.dll
      C:\Program Files\MiKTeX 2.9\miktex\bin\x64\api-ms-win-core-util-l1-1-0.dll
      C:\Program Files\MiKTeX 2.9\miktex\bin\x64\api-ms-win-core-profile-l1-1-0.dll
      C:\Program Files\MiKTeX 2.9\miktex\bin\x64\api-ms-win-core-file-l2-1-0.dll
      C:\Program Files\MiKTeX 2.9\miktex\bin\x64\api-ms-win-core-console-l1-1-0.dll
  C:\cygwin64\bin\cyggcc_s-seh-1.dll
  C:\cygwin64\bin\cyggomp-1.dll
  C:\cygwin64\bin\cygstdc++-6.dll
cygcheck: track_down: could not find cygboost_serialization-1_66.dll

  C:\cygwin64\bin\cygbz2-1.dll
  C:\cygwin64\bin\cygexpat-1.dll
  C:\cygwin64\bin\cyggdal-26.dll
    C:\cygwin64\bin\cygcfitsio-7.dll
      C:\cygwin64\bin\cygcurl-4.dll
        C:\cygwin64\bin\cygbrotlidec-1.dll
          C:\cygwin64\bin\cygbrotlicommon-1.dll
        C:\cygwin64\bin\cygcrypto-1.1.dll
          C:\cygwin64\bin\cygz.dll
        C:\cygwin64\bin\cyggssapi_krb5-2.dll
          C:\cygwin64\bin\cygk5crypto-3.dll
            C:\cygwin64\bin\cygkrb5support-0.dll
              C:\cygwin64\bin\cygintl-8.dll
                C:\cygwin64\bin\cygiconv-2.dll
          C:\cygwin64\bin\cygkrb5-3.dll
            C:\cygwin64\bin\cygcom_err-2.dll
        C:\cygwin64\bin\cygidn2-0.dll
          C:\cygwin64\bin\cygunistring-2.dll
        C:\cygwin64\bin\cyglber-2-4-2.dll
        C:\cygwin64\bin\cygldap-2-4-2.dll
          C:\cygwin64\bin\cygsasl2-3.dll
          C:\cygwin64\bin\cygssl-1.1.dll
        C:\cygwin64\bin\cygnghttp2-14.dll
        C:\cygwin64\bin\cygpsl-5.dll
        C:\cygwin64\bin\cygssh-4.dll
    C:\cygwin64\bin\cyggeos_c-1.dll
      C:\cygwin64\bin\cyggeos-3-8-0.dll
    C:\cygwin64\bin\cyggeotiff-5.dll
      C:\cygwin64\bin\cygproj-15.dll
        C:\cygwin64\bin\cygsqlite3-0.dll
      C:\cygwin64\bin\cygtiff-6.dll
        C:\cygwin64\bin\cygjbig-2.dll
        C:\cygwin64\bin\cygjpeg-8.dll
        C:\cygwin64\bin\cyglzma-5.dll
    C:\cygwin64\bin\cyggif-7.dll
    C:\cygwin64\bin\cyghdf5-103.dll
    C:\cygwin64\bin\cygjson-c-2.dll
    C:\cygwin64\bin\cygnetcdf-15.dll
      C:\cygwin64\bin\cyghdf5_hl-100.dll
    C:\cygwin64\bin\cygopenjp2-7.dll
    C:\cygwin64\bin\cygpcre-1.dll
    C:\cygwin64\bin\cygpng16-16.dll
    C:\cygwin64\bin\cygpq-5.dll
      C:\cygwin64\bin\cygldap_r-2-4-2.dll
    C:\cygwin64\bin\cygqhull-7.dll
    C:\cygwin64\bin\cygwebp-7.dll
    C:\cygwin64\bin\cygxml2-2.dll
    C:\WINDOWS\system32\ODBC32.dll
      C:\WINDOWS\system32\msvcrt.dll
      C:\WINDOWS\system32\CRYPT32.dll
        C:\Program Files\MiKTeX 2.9\miktex\bin\x64\api-ms-win-crt-runtime-l1-1-0.dll
        C:\Program Files\MiKTeX 2.9\miktex\bin\x64\api-ms-win-crt-string-l1-1-0.dll
        C:\Program Files\MiKTeX 2.9\miktex\bin\x64\api-ms-win-crt-private-l1-1-0.dll
        C:\Program Files\MiKTeX 2.9\miktex\bin\x64\api-ms-win-core-interlocked-l1-1-0.dll
        C:\WINDOWS\system32\MSASN1.dll
      C:\WINDOWS\system32\ADVAPI32.dll
        C:\WINDOWS\system32\SECHOST.dll
          C:\WINDOWS\system32\RPCRT4.dll
      C:\WINDOWS\system32\USER32.dll
        C:\WINDOWS\system32\win32u.dll
        C:\WINDOWS\system32\GDI32.dll
    C:\WINDOWS\system32\ODBCCP32.dll
      C:\WINDOWS\system32\VERSION.dll
    C:\WINDOWS\system32\WS2_32.dll

```

**Comment by cyang-kth** [comment]
Maybe you need to reinstall the boost dependency with 
```
apt-cyg install make libboost-devel
```

**Comment by gottfriedmrs** [comment]
I found that I didn't have all the rights (-rwx and so on) on the root directory of cygwin ( C:/cygwin64 ), so I changed this to install the packages properly (I had some 'Permission denied' lines before this when I did apt-cyg install make for example)

Now I got the following issues (see after 21%):

```
XXXXX@XXXXX~
$ apt-cyg install make libboost-devel
make-4.3-1.tar.xz: Réussi
libboost-devel-1.66.0-1.tar.xz: Réussi

XXXXX@XXXXX~
$ cd fmm/build/

XXXXX@XXXXX~/fmm/build
$ cmake ..
-- CMAKE version 3.17.3
-- Set CMP0074 state to NEW
-- Set CMP0086 state to NEW
-- Set CMP0078 state to NEW
-- OSMium found at third_party/libosmium/include;/usr/include;third_party/protozero/include
-- OSMium library found at /usr/lib/libz.dll.a;/usr/lib/libexpat.dll.a;/usr/lib/libbz2.dll.a
-- GDAL headers found at /usr/include
-- GDAL library found at /usr/lib/libgdal.dll.a
-- Found Boost: /usr/include (found suitable version "1.66.0", minimum required is "1.54.0") found components: serialization
-- Boost headers found at /usr/include
-- Boost library found at /usr/lib/libboost_serialization.dll.a
-- Boost library version 1_66
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- OpenMP_HEADERS found at
-- OpenMP_CXX_LIBRARIES found at /usr/lib/gcc/x86_64-pc-cygwin/9.3.0/libgomp.dll.a
-- Found SWIG: /usr/bin/swig.exe (found version "3.0.12")
-- Swig version is 3.0.12
-- Found PythonLibs: /usr/lib/libpython2.7.dll.a (found suitable version "2.7.18", minimum required is "2.7")
-- Python header found at /usr/include/python2.7
-- Python library found at /usr/lib/libpython2.7.dll.a
-- Using swig add library
-- Configuring done
-- Generating done
-- Build files have been written to: /home/XXXXX/fmm/build

XXXXX@XXXXX~/fmm/build
$ make -j8
Scanning dependencies of target UTILScanning dependencies of target CORE

Scanning dependencies of target CONFIGScanning dependencies of target IOScanning dependencies of target FMM_OBJ


Scanning dependencies of target NETWORKScanning dependencies of target MM_OBJ

Scanning dependencies of target ALGORITHM[  5%] [  2%] Building CXX object CMakeFiles/CONFIG.dir/src/config/gps_config.cpp.o
Building CXX object CMakeFiles/CORE.dir/src/core/geometry.cpp.o

[ 10%] Building CXX object CMakeFiles/UTIL.dir/src/util/util.cpp.o[ 13%] [ 10%]
Building CXX object CMakeFiles/IO.dir/src/io/gps_reader.cpp.oBuilding CXX object CMakeFiles/MM_OBJ.dir/src/mm/composite_graph.cpp.oBuilding CXX object CMakeFiles/MM_OBJ.dir/src/mm/composite_graph.cpp.o

[ 15%] Building CXX object CMakeFiles/FMM_OBJ.dir/src/mm/fmm/fmm_algorithm.cpp.oBuilding CXX object CMakeFiles/FMM_OBJ.dir/src/mm/fmm/fmm_algorithm.cpp.o
[ 21%] [ 21%] Building CXX object CMakeFiles/ALGORITHM.dir/src/algorithm/geom_algorithm.cpp.o
Building CXX object CMakeFiles/NETWORK.dir/src/network/bidirectional_network_graph.cpp.o
/home/XXXXX/fmm/src/core/geometry.cpp:10:10: erreur fatale: boost/geometry/extensions/gis/io/wkb/read_wkb.hpp : No such file or directory
   10 | #include "boost/geometry/extensions/gis/io/wkb/read_wkb.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminée.
make[2]: *** [CMakeFiles/CORE.dir/build.make:83 : CMakeFiles/CORE.dir/src/core/geometry.cpp.o] Erreur 1
make[1]: *** [CMakeFiles/Makefile2:225 : CMakeFiles/CORE.dir/all] Erreur 2
make[1]: *** Attente des tâches non terminées....
[ 23%] Building CXX object CMakeFiles/IO.dir/src/io/mm_writer.cpp.o
[ 23%] Built target UTIL
[ 26%] Building CXX object CMakeFiles/MM_OBJ.dir/src/mm/transition_graph.cpp.o
[ 26%] Built target ALGORITHM
[ 28%] Building CXX object CMakeFiles/FMM_OBJ.dir/src/mm/fmm/fmm_app.cpp.o
[ 31%] Building CXX object CMakeFiles/CONFIG.dir/src/config/network_config.cpp.o
[ 34%] Building CXX object CMakeFiles/FMM_OBJ.dir/src/mm/fmm/fmm_app_config.cpp.o[ 34%] Built target MM_OBJ

[ 36%] Building CXX object CMakeFiles/CONFIG.dir/src/config/result_config.cpp.o
[ 39%] Building CXX object CMakeFiles/NETWORK.dir/src/network/network.cpp.o
[ 42%] Building CXX object CMakeFiles/NETWORK.dir/src/network/network_graph.cpp.o
[ 42%] Built target IO
[ 44%] Building CXX object CMakeFiles/FMM_OBJ.dir/src/mm/fmm/ubodt.cpp.o
[ 47%] Building CXX object CMakeFiles/FMM_OBJ.dir/src/mm/fmm/ubodt_gen_algorithm.cpp.o
[ 50%] Building CXX object CMakeFiles/FMM_OBJ.dir/src/mm/fmm/ubodt_gen_app.cpp.o
[ 52%] Building CXX object CMakeFiles/FMM_OBJ.dir/src/mm/fmm/ubodt_gen_app_config.cpp.o
[ 55%] Building CXX object CMakeFiles/NETWORK.dir/src/network/rtree.cpp.o
[ 55%] Built target CONFIG
[ 55%] Built target NETWORK
[ 55%] Built target FMM_OBJ
make: *** [Makefile:150 : all] Erreur 2

```

**Comment by cyang-kth** [comment]
I think that it would be better if you delete the build folder completely and create a new one to install when you make some changes. That error is strange as the file is already included in the third-party folder. 

You could also compare your log with this one here:
https://ci.appveyor.com/project/cyang-kth/fmm#L3006

**Comment by gottfriedmrs** [comment]
Thank you cyang, issue solved by reinstalling Cygwin and ask for permissions in Cygwin / folder:

chown -R [USERNAME] /*
