### ISSUE TITLE
Python import UBODTGenAlgorithm

### ISSUE THREAD

**Issue by williamgrimes** [cyang-kth/fmm#108]
@cyang-kth, I'm following your notebook to try and run FMM with Python3.8

https://github.com/cyang-kth/fmm/blob/master/example/notebook/fmm_example.ipynb

When running the following 

```
from fmm import Network,NetworkGraph,FastMapMatch,FastMapMatchConfig,UBODT
from fmm import UBODTGenAlgorithm
```

I get the following error

```
python-BaseException
...
ImportError: cannot import name 'UBODTGenAlgorithm' from 'fmm' (/opt/fmm/build/python/fmm.py)
```
Any idea what could be the issue? Thanks

**Comment by cyang-kth** [comment]
Do you have multiple version of Python installed? Did you install the program also with Python 3.8 or 2.7?

From the `cmake ..` you should be able to see the version of Python library.  Like this one below

https://travis-ci.org/github/cyang-kth/fmm/jobs/720923947#L870

**Comment by williamgrimes** [comment]
`cmake ..`

```
-- CMAKE version 3.10.2
-- OSMium found at third_party/libosmium/include;/usr/include;third_party/protozero/include
-- OSMium library found at /usr/lib/x86_64-linux-gnu/libz.so;-lpthread;/usr/lib/x86_64-linux-gnu/libexpat.so;/usr/lib/x86_64-linux-gnu/libbz2.so
-- GDAL headers found at /usr/include/gdal
-- GDAL library found at /usr/lib/libgdal.so
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   serialization
-- Boost headers found at /usr/include
-- Boost library found at /usr/lib/x86_64-linux-gnu/libboost_serialization.so
-- Boost library version 1_65_1
-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP: TRUE   
-- OpenMP_HEADERS found at 
-- OpenMP_CXX_LIBRARIES found at /usr/lib/gcc/x86_64-linux-gnu/7/libgomp.so;/usr/lib/x86_64-linux-gnu/libpthread.so
-- Swig version is 3.0.12
-- Python header found at /usr/include/python3.8
-- Python library found at /usr/lib
-- Using swig add module
CMake Deprecation Warning at /usr/share/cmake-3.10/Modules/UseSWIG.cmake:231 (message):
  SWIG_ADD_MODULE is deprecated.  Use SWIG_ADD_LIBRARY instead.
Call Stack (most recent call first):
  python/CMakeLists.txt:51 (SWIG_ADD_MODULE)


-- Configuring done
WARNING: Target "_fmm" requests linking to directory "/usr/lib".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /opt/fmm/build
```

Yes I do have multiple versions of python and by default it instaleld to python2.7, then I installed on python3.8 as 

```
cmake .. -DPYTHON_INCLUDE_DIR=$(python3.8 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())") -DPYTHON_LIBRARY=$(python3.8 -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))") -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3.8
```


```
-- CMAKE version 3.10.2
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found Protozero: third_party/protozero/include (found suitable version "1.6.2", minimum required is "1.5.1")
-- Found EXPAT: /usr/lib/x86_64-linux-gnu/libexpat.so (found version "2.2.5")
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6")
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found Osmium: third_party/libosmium/include
-- OSMium found at third_party/libosmium/include;/usr/include;third_party/protozero/include
-- OSMium library found at /usr/lib/x86_64-linux-gnu/libz.so;-lpthread;/usr/lib/x86_64-linux-gnu/libexpat.so;/usr/lib/x86_64-linux-gnu/libbz2.so
-- Found GDAL: /usr/lib/libgdal.so (Required is at least version "2.2")
-- GDAL headers found at /usr/include/gdal
-- GDAL library found at /usr/lib/libgdal.so
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   serialization
-- Boost headers found at /usr/include
-- Boost library found at /usr/lib/x86_64-linux-gnu/libboost_serialization.so
-- Boost library version 1_65_1
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- OpenMP_HEADERS found at
-- OpenMP_CXX_LIBRARIES found at /usr/lib/gcc/x86_64-linux-gnu/7/libgomp.so;/usr/lib/x86_64-linux-gnu/libpthread.so
-- Found SWIG: /usr/bin/swig3.0 (found version "3.0.12")
-- Swig version is 3.0.12
-- Found PythonLibs: /usr/lib (found suitable version "3.8.3", minimum required is "2.7")
-- Python header found at /usr/include/python3.8
-- Python library found at /usr/lib
-- Using swig add module
CMake Deprecation Warning at /usr/share/cmake-3.10/Modules/UseSWIG.cmake:231 (message):
  SWIG_ADD_MODULE is deprecated.  Use SWIG_ADD_LIBRARY instead.
Call Stack (most recent call first):
  python/CMakeLists.txt:51 (SWIG_ADD_MODULE)


-- Configuring done
WARNING: Target "_fmm" requests linking to directory "/usr/lib".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /opt/fmm/build
```

`make -j4`

```
Scanning dependencies of target NETWORK
Scanning dependencies of target CONFIG
Scanning dependencies of target CORE
Scanning dependencies of target UTIL
[  5%] Building CXX object CMakeFiles/UTIL.dir/src/util/util.cpp.o
[  5%] Building CXX object CMakeFiles/CORE.dir/src/core/geometry.cpp.o
[  8%] Building CXX object CMakeFiles/CONFIG.dir/src/config/gps_config.cpp.o
[ 11%] Building CXX object CMakeFiles/NETWORK.dir/src/network/bidirectional_network_graph.cpp.o
[ 11%] Built target UTIL
Scanning dependencies of target IO
[ 13%] Building CXX object CMakeFiles/IO.dir/src/io/gps_reader.cpp.o
[ 13%] Built target CORE
Scanning dependencies of target ALGORITHM
[ 16%] Building CXX object CMakeFiles/ALGORITHM.dir/src/algorithm/geom_algorithm.cpp.o
[ 19%] Building CXX object CMakeFiles/NETWORK.dir/src/network/network.cpp.o
[ 19%] Built target ALGORITHM
Scanning dependencies of target MM_OBJ
[ 22%] Building CXX object CMakeFiles/MM_OBJ.dir/src/mm/composite_graph.cpp.o
[ 25%] Building CXX object CMakeFiles/CONFIG.dir/src/config/network_config.cpp.o
[ 27%] Building CXX object CMakeFiles/IO.dir/src/io/mm_writer.cpp.o
[ 30%] Building CXX object CMakeFiles/MM_OBJ.dir/src/mm/transition_graph.cpp.o
[ 33%] Building CXX object CMakeFiles/CONFIG.dir/src/config/result_config.cpp.o
[ 33%] Built target IO
Scanning dependencies of target FMM_OBJ
[ 36%] Building CXX object CMakeFiles/FMM_OBJ.dir/src/mm/fmm/fmm_algorithm.cpp.o
[ 38%] Building CXX object CMakeFiles/NETWORK.dir/src/network/network_graph.cpp.o
[ 38%] Built target MM_OBJ
[ 41%] Building CXX object CMakeFiles/FMM_OBJ.dir/src/mm/fmm/fmm_app.cpp.o
[ 41%] Built target CONFIG
Scanning dependencies of target STMATCH_OBJ
[ 44%] Building CXX object CMakeFiles/STMATCH_OBJ.dir/src/mm/stmatch/stmatch_algorithm.cpp.o
[ 47%] Building CXX object CMakeFiles/FMM_OBJ.dir/src/mm/fmm/fmm_app_config.cpp.o
[ 50%] Building CXX object CMakeFiles/NETWORK.dir/src/network/rtree.cpp.o
[ 52%] Building CXX object CMakeFiles/FMM_OBJ.dir/src/mm/fmm/ubodt.cpp.o
[ 52%] Built target NETWORK
Scanning dependencies of target PYTHONSTMATCH_OBJ
[ 55%] Building CXX object python/CMakeFiles/PYTHONSTMATCH_OBJ.dir/__/src/mm/stmatch/stmatch_algorithm.cpp.o
[ 58%] Building CXX object CMakeFiles/STMATCH_OBJ.dir/src/mm/stmatch/stmatch_app.cpp.o
[ 61%] Building CXX object CMakeFiles/FMM_OBJ.dir/src/mm/fmm/ubodt_gen_app.cpp.o
[ 63%] Building CXX object CMakeFiles/FMM_OBJ.dir/src/mm/fmm/ubodt_gen_app_config.cpp.o
[ 63%] Built target PYTHONSTMATCH_OBJ
Scanning dependencies of target PYTHONFMM_OBJ
[ 66%] Building CXX object python/CMakeFiles/PYTHONFMM_OBJ.dir/__/src/mm/fmm/fmm_algorithm.cpp.o
[ 69%] Building CXX object CMakeFiles/STMATCH_OBJ.dir/src/mm/stmatch/stmatch_app_config.cpp.o
[ 72%] Building CXX object python/CMakeFiles/PYTHONFMM_OBJ.dir/__/src/mm/fmm/ubodt.cpp.o
[ 72%] Built target FMM_OBJ
Scanning dependencies of target fmm
[ 75%] Building CXX object CMakeFiles/fmm.dir/src/app/fmm.cpp.o
Scanning dependencies of target ubodt_gen
[ 77%] Building CXX object CMakeFiles/ubodt_gen.dir/src/app/ubodt_gen_app.cpp.o
[ 77%] Built target PYTHONFMM_OBJ
Scanning dependencies of target pyfmmlib
[ 80%] Linking CXX shared library libpyfmmlib.so
[ 80%] Built target pyfmmlib
[ 83%] Swig source
Scanning dependencies of target _fmm
[ 86%] Building CXX object python/CMakeFiles/_fmm.dir/fmmPYTHON_wrap.cxx.o
[ 86%] Built target STMATCH_OBJ
Scanning dependencies of target stmatch
[ 88%] Building CXX object CMakeFiles/stmatch.dir/src/app/stmatch.cpp.o
[ 91%] Linking CXX executable fmm
[ 94%] Linking CXX executable ubodt_gen
[ 94%] Built target fmm
[ 94%] Built target ubodt_gen
[ 97%] Linking CXX executable stmatch
[ 97%] Built target stmatch
[100%] Linking CXX shared module _fmm.so
[100%] Built target _fmm
```

`sudo make install`

```[ 11%] Built target NETWORK
[ 13%] Built target CORE
[ 22%] Built target CONFIG
[ 25%] Built target UTIL
[ 30%] Built target IO
[ 33%] Built target ALGORITHM
[ 38%] Built target MM_OBJ
[ 55%] Built target FMM_OBJ
[ 61%] Built target fmm
[ 66%] Built target ubodt_gen
[ 75%] Built target STMATCH_OBJ
[ 80%] Built target stmatch
[ 83%] Built target PYTHONSTMATCH_OBJ
[ 88%] Built target PYTHONFMM_OBJ
[ 91%] Built target pyfmmlib
[100%] Built target _fmm
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/bin/fmm
-- Installing: /usr/local/bin/ubodt_gen
-- Installing: /usr/local/bin/stmatch
```

**Comment by cyang-kth** [comment]
From your log, it seems that fmm is correctly installed. 

If you directly run this two line in your python 3. terminal, will you still see the same error?
```python
from fmm import Network,NetworkGraph,FastMapMatch,FastMapMatchConfig,UBODT
from fmm import UBODTGenAlgorithm
```

**Comment by williamgrimes** [comment]
```
Python 3.8.3 (default, May 14 2020, 20:11:43) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from fmm import Network,NetworkGraph,FastMapMatch,FastMapMatchConfig,UBODT
>>> from fmm import UBODTGenAlgorithm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'UBODTGenAlgorithm' from 'fmm' (/opt/fmm/build/python/fmm.py)
>>> 
```

**Comment by cyang-kth** [comment]
I am not quite sure if this issue is helpful. 

https://github.com/cyang-kth/fmm/issues/5#issuecomment-624574827

It seems to work on Python 3. 

This setting is missing in the current version 

```
set_property(TARGET pyfmm PROPERTY SWIG_COMPILE_OPTIONS -py3)
```

https://github.com/cyang-kth/fmm/blob/7c80e8ae256322bdac20ec019d2134af706af9c5/python/CMakeLists.txt#L64

I also found that `SWIG_COMPILE_OPTIONS` is not available for your CMake version. Maybe you can consider upgrade the cmake.

**Comment by williamgrimes** [comment]
Upgraded CMAKE version and edited the line:

https://github.com/cyang-kth/fmm/blob/7c80e8ae256322bdac20ec019d2134af706af9c5/python/CMakeLists.txt#L64

Still no luck

`cmake .. -DPYTHON_INCLUDE_DIR=$(python3.8 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())") -DPYTHON_LIBRARY=$(python3.8 -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))") -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3.8`

```
-- CMAKE version 3.18.2
-- Set CMP0074 state to NEW
-- Set CMP0086 state to NEW
-- Set CMP0078 state to NEW
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found Protozero: third_party/protozero/include (found suitable version "1.6.2", minimum required is "1.5.1")
-- Found EXPAT: /usr/lib/x86_64-linux-gnu/libexpat.so (found version "2.2.5")
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6")
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found Osmium: third_party/libosmium/include
-- OSMium found at third_party/libosmium/include;/usr/include;third_party/protozero/include
-- OSMium library found at /usr/lib/x86_64-linux-gnu/libz.so;-lpthread;/usr/lib/x86_64-linux-gnu/libexpat.so;/usr/lib/x86_64-linux-gnu/libbz2.so
-- Found GDAL: /usr/lib/libgdal.so (found suitable version "2.4.2", minimum required is "2.2")
-- GDAL headers found at /usr/include/gdal
-- GDAL library found at /usr/lib/libgdal.so
-- Found Boost: /usr/include (found suitable version "1.65.1", minimum required is "1.54.0") found components: serialization
-- Boost headers found at /usr/include
-- Boost library found at /usr/lib/x86_64-linux-gnu/libboost_serialization.so
-- Boost library version 1_65_1
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- OpenMP_HEADERS found at
-- OpenMP_CXX_LIBRARIES found at /usr/lib/gcc/x86_64-linux-gnu/7/libgomp.so;/usr/lib/x86_64-linux-gnu/libpthread.so
-- Found SWIG: /usr/bin/swig3.0 (found version "3.0.12")
-- Swig version is 3.0.12
-- Found PythonLibs: /usr/lib (found suitable version "3.8.3", minimum required is "2.7")
-- Python header found at /usr/include/python3.8
-- Python library found at /usr/lib
-- Using swig add library
-- Configuring done
WARNING: Target "pyfmm" requests linking to directory "/usr/lib".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /opt/fmm/build
```

`make -j4`
```
Scanning dependencies of target NETWORK
Scanning dependencies of target CONFIG
Scanning dependencies of target CORE
Scanning dependencies of target UTIL
[  2%] Building CXX object CMakeFiles/UTIL.dir/src/util/util.cpp.o
[  5%] Building CXX object CMakeFiles/CORE.dir/src/core/geometry.cpp.o
[  8%] Building CXX object CMakeFiles/CONFIG.dir/src/config/gps_config.cpp.o
[ 11%] Building CXX object CMakeFiles/NETWORK.dir/src/network/bidirectional_network_graph.cpp.o
[ 11%] Built target UTIL
[ 13%] Building CXX object CMakeFiles/NETWORK.dir/src/network/network.cpp.o
[ 13%] Built target CORE
Scanning dependencies of target IO
[ 16%] Building CXX object CMakeFiles/IO.dir/src/io/gps_reader.cpp.o
[ 19%] Building CXX object CMakeFiles/NETWORK.dir/src/network/network_graph.cpp.o
[ 22%] Building CXX object CMakeFiles/CONFIG.dir/src/config/network_config.cpp.o
[ 25%] Building CXX object CMakeFiles/IO.dir/src/io/mm_writer.cpp.o
[ 27%] Building CXX object CMakeFiles/NETWORK.dir/src/network/rtree.cpp.o
Scanning dependencies of target ALGORITHM
[ 30%] Building CXX object CMakeFiles/ALGORITHM.dir/src/algorithm/geom_algorithm.cpp.o
[ 33%] Building CXX object CMakeFiles/CONFIG.dir/src/config/result_config.cpp.o
[ 33%] Built target NETWORK
Scanning dependencies of target MM_OBJ
[ 36%] Building CXX object CMakeFiles/MM_OBJ.dir/src/mm/composite_graph.cpp.o
[ 36%] Built target IO
Scanning dependencies of target FMM_OBJ
[ 38%] Building CXX object CMakeFiles/FMM_OBJ.dir/src/mm/fmm/fmm_algorithm.cpp.o
[ 38%] Built target ALGORITHM
Scanning dependencies of target STMATCH_OBJ
[ 41%] Building CXX object CMakeFiles/STMATCH_OBJ.dir/src/mm/stmatch/stmatch_algorithm.cpp.o
[ 41%] Built target CONFIG
Scanning dependencies of target PYTHONSTMATCH_OBJ
[ 44%] Building CXX object python/CMakeFiles/PYTHONSTMATCH_OBJ.dir/__/src/mm/stmatch/stmatch_algorithm.cpp.o
[ 47%] Building CXX object CMakeFiles/MM_OBJ.dir/src/mm/transition_graph.cpp.o
[ 50%] Building CXX object CMakeFiles/FMM_OBJ.dir/src/mm/fmm/fmm_app.cpp.o
[ 50%] Built target MM_OBJ
Scanning dependencies of target PYTHONFMM_OBJ
[ 52%] Building CXX object python/CMakeFiles/PYTHONFMM_OBJ.dir/__/src/mm/fmm/fmm_algorithm.cpp.o
[ 55%] Building CXX object CMakeFiles/STMATCH_OBJ.dir/src/mm/stmatch/stmatch_app.cpp.o
[ 55%] Built target PYTHONSTMATCH_OBJ
[ 58%] Building CXX object python/CMakeFiles/PYTHONFMM_OBJ.dir/__/src/mm/fmm/ubodt.cpp.o
[ 61%] Building CXX object CMakeFiles/FMM_OBJ.dir/src/mm/fmm/fmm_app_config.cpp.o
[ 63%] Building CXX object CMakeFiles/FMM_OBJ.dir/src/mm/fmm/ubodt.cpp.o
[ 66%] Building CXX object CMakeFiles/STMATCH_OBJ.dir/src/mm/stmatch/stmatch_app_config.cpp.o
[ 66%] Built target PYTHONFMM_OBJ
Scanning dependencies of target pyfmm_swig_compilation
[ 69%] Swig compile /opt/fmm/python/fmm.i for python
[ 69%] Built target pyfmm_swig_compilation
Scanning dependencies of target pyfmmlib
[ 72%] Linking CXX shared library libpyfmmlib.so
[ 72%] Built target pyfmmlib
Scanning dependencies of target pyfmm
[ 75%] Building CXX object python/CMakeFiles/pyfmm.dir/CMakeFiles/pyfmm.dir/fmmPYTHON_wrap.cxx.o
[ 77%] Building CXX object CMakeFiles/FMM_OBJ.dir/src/mm/fmm/ubodt_gen_app.cpp.o
[ 80%] Building CXX object CMakeFiles/FMM_OBJ.dir/src/mm/fmm/ubodt_gen_app_config.cpp.o
[ 80%] Built target STMATCH_OBJ
Scanning dependencies of target stmatch
[ 83%] Building CXX object CMakeFiles/stmatch.dir/src/app/stmatch.cpp.o
[ 86%] Linking CXX shared module _pyfmm.so
[ 86%] Built target pyfmm
[ 86%] Built target FMM_OBJ
Scanning dependencies of target fmm
Scanning dependencies of target ubodt_gen
[ 88%] Building CXX object CMakeFiles/ubodt_gen.dir/src/app/ubodt_gen_app.cpp.o
[ 91%] Building CXX object CMakeFiles/fmm.dir/src/app/fmm.cpp.o
[ 94%] Linking CXX executable stmatch
[ 94%] Built target stmatch
[ 97%] Linking CXX executable ubodt_gen
[ 97%] Built target ubodt_gen
[100%] Linking CXX executable fmm
[100%] Built target fmm
```
`sudo make install`
```
[ 11%] Built target NETWORK
[ 13%] Built target CORE
[ 22%] Built target CONFIG
[ 25%] Built target UTIL
[ 30%] Built target IO
[ 33%] Built target ALGORITHM
[ 38%] Built target MM_OBJ
[ 55%] Built target FMM_OBJ
[ 61%] Built target fmm
[ 66%] Built target ubodt_gen
[ 75%] Built target STMATCH_OBJ
[ 80%] Built target stmatch
[ 83%] Built target PYTHONSTMATCH_OBJ
[ 88%] Built target PYTHONFMM_OBJ
[ 91%] Built target pyfmmlib
[ 94%] Built target pyfmm_swig_compilation
[100%] Built target pyfmm
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/bin/fmm
-- Installing: /usr/local/bin/ubodt_gen
-- Installing: /usr/local/bin/stmatch
```

**Comment by williamgrimes** [comment]
Is this WARNING relevant

`WARNING: Target "pyfmm" requests linking to directory "/usr/lib".  Targets may link only to libraries.  CMake is dropping the item.`

**Comment by cyang-kth** [comment]
@williamgrimes 
It seems that you need to specify the file path rather than a directory, like this one shown below:

```bash
cmake .. -DPYTHON_LIBRARY=/home/cyang/anaconda2/lib/libpython2.7.so
```

**Comment by williamgrimes** [comment]
Tried again with:
```
cmake ..
    -DPYTHON_INCLUDE_DIR=/usr/include/python3.8
    -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.8.so
    -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3.8
```
and `CMakeLists.txt` file as

```
# Make sure the swig package is loaded.
find_package(SWIG REQUIRED)
include(${SWIG_USE_FILE})
if (SWIG_FOUND)
  message(STATUS "Swig version is ${SWIG_VERSION}")
else()
  message(FATAL_ERROR "Swig not found!\n")
endif()

find_package(PythonLibs 3.8 REQUIRED)
if (PYTHONLIBS_FOUND)
  message(STATUS "Python header found at ${PYTHON_INCLUDE_DIRS}")
  message(STATUS "Python library found at ${PYTHON_LIBRARIES}")
  include_directories(${PYTHON_INCLUDE_DIRS})
else()
  message(FATAL_ERROR "Python library not found!\n")
endif()

file(GLOB PYTHONFMMGlob
${PROJECT_SOURCE_DIR}/src/mm/fmm/fmm_algorithm.cpp
${PROJECT_SOURCE_DIR}/src/mm/fmm/ubodt.cpp)
file(GLOB PYTHONSTMATCHGlob
${PROJECT_SOURCE_DIR}/src/mm/stmatch/stmatch_algorithm.cpp)

add_library(PYTHONFMM_OBJ OBJECT ${PYTHONFMMGlob})
add_library(PYTHONSTMATCH_OBJ OBJECT ${PYTHONSTMATCHGlob})

set_source_files_properties(
${PROJECT_SOURCE_DIR}/python/fmm.i PROPERTIES CPLUSPLUS ON)
set_source_files_properties(
${PROJECT_SOURCE_DIR}/python/fmm.i PROPERTIES SWIG_FLAGS "")

add_library(pyfmmlib SHARED
$<TARGET_OBJECTS:MM_OBJ>
$<TARGET_OBJECTS:PYTHONFMM_OBJ>
$<TARGET_OBJECTS:PYTHONSTMATCH_OBJ>
$<TARGET_OBJECTS:CORE>
$<TARGET_OBJECTS:CONFIG>
$<TARGET_OBJECTS:ALGORITHM>
$<TARGET_OBJECTS:UTIL>
$<TARGET_OBJECTS:NETWORK>)

set_property(TARGET pyfmmlib PROPERTY POSITION_INDEPENDENT_CODE ON)
target_link_libraries(pyfmmlib ${GDAL_LIBRARIES} ${Boost_LIBRARIES}
${OSMIUM_LIBRARIES})
# Add the target.
if (${CMAKE_VERSION} VERSION_LESS 3.13.0)
  message(STATUS "Using swig add module")
  set_property(SOURCE ${PROJECT_SOURCE_DIR}/python/fmm.i
    PROPERTY SWIG_MODULE_NAME fmm)
  SWIG_ADD_MODULE(fmm python ${PROJECT_SOURCE_DIR}/python/fmm.i)
  swig_link_libraries(fmm
          ${PYTHON_LIBRARIES}
          ${Boost_LIBRARIES}
          ${OSMIUM_LIBRARIES}
          pyfmmlib)
else()
  message(STATUS "Using swig add library")
  SWIG_ADD_LIBRARY(pyfmm
    LANGUAGE python
    SOURCES ${PROJECT_SOURCE_DIR}/python/fmm.i)
  #set_property(TARGET pyfmm PROPERTY OUTPUT_NAME fmm)
  set_property(TARGET pyfmm PROPERTY SWIG_COMPILE_OPTIONS -py3)
  swig_link_libraries(pyfmm
          ${PYTHON_LIBRARIES}
          ${Boost_LIBRARIES}
          ${OSMIUM_LIBRARIES}
          pyfmmlib)
endif()
```

Output looks fine, no warning this time

```
-- CMAKE version 3.18.2
-- Set CMP0074 state to NEW
-- Set CMP0086 state to NEW
-- Set CMP0078 state to NEW
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found Protozero: third_party/protozero/include (found suitable version "1.6.2", minimum required is "1.5.1")
-- Found EXPAT: /usr/lib/x86_64-linux-gnu/libexpat.so (found version "2.2.5")
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6")
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found Osmium: third_party/libosmium/include
-- OSMium found at third_party/libosmium/include;/usr/include;third_party/protozero/include
-- OSMium library found at /usr/lib/x86_64-linux-gnu/libz.so;-lpthread;/usr/lib/x86_64-linux-gnu/libexpat.so;/usr/lib/x86_64-linux-gnu/libbz2.so
-- Found GDAL: /usr/lib/libgdal.so (found suitable version "2.4.2", minimum required is "2.2")
-- GDAL headers found at /usr/include/gdal
-- GDAL library found at /usr/lib/libgdal.so
-- Found Boost: /usr/include (found suitable version "1.65.1", minimum required is "1.54.0") found components: serialization
-- Boost headers found at /usr/include
-- Boost library found at /usr/lib/x86_64-linux-gnu/libboost_serialization.so
-- Boost library version 1_65_1
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- OpenMP_HEADERS found at
-- OpenMP_CXX_LIBRARIES found at /usr/lib/gcc/x86_64-linux-gnu/7/libgomp.so;/usr/lib/x86_64-linux-gnu/libpthread.so
-- Found SWIG: /usr/bin/swig3.0 (found version "3.0.12")
-- Swig version is 3.0.12
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found suitable version "3.8.3", minimum required is "3.8")
-- Python header found at /usr/include/python3.8
-- Python library found at /usr/lib/x86_64-linux-gnu/libpython3.8.so
-- Using swig add library
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/fmm/build
```

But still import does not work

```
Python 3.8.3 (default, May 14 2020, 20:11:43)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from fmm import Network,NetworkGraph,FastMapMatch,FastMapMatchConfig,UBODT
>>> from fmm import UBODTGenAlgorithm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'UBODTGenAlgorithm' from 'fmm' (/opt/fmm/build/python/fmm.py)
```

**Comment by cyang-kth** [comment]
@williamgrimes 

Will you be able to run this example notebook
https://github.com/cyang-kth/fmm/blob/master/example/notebook/stmatch_example.ipynb

I wonder if it is just that specific class or something else is also wrong. Perhaps the `opt/fmm` has some permission issue?

Are you able to run these command line examples like `fmm`,`stmatch`,`ubodt_gen`?

**Comment by williamgrimes** [comment]
https://github.com/cyang-kth/fmm/blob/master/example/notebook/stmatch_example.ipynb

The example notebooks works. The problem seems to be specifically with 

`from fmm import UBODTGenAlgorithm`

All the command line examples of `fmm`, `stmatch`, and `ubodt_gen` seem to work.

For now I'll create the ubodt file via the command line so I can proceed...

**Comment by williamgrimes** [comment]
This is what the `fmm.py` file looks like there is no mention of `UBODTGenAlgorithm`

[fmm.py.txt](https://github.com/cyang-kth/fmm/files/5194182/fmm.py.txt)

**Comment by cyang-kth** [comment]
@williamgrimes 
Which version are you compiling the project? Is it the master version?

Not only the UBODTGenAlgorithm but also GPSConfig, OutputConfig, ResultConfig are missing from your python file. 

It seems that maybe you are working on an old version of the program. Did you pull the latest version?

**Comment by williamgrimes** [comment]
Whoops I was working with master branch with last commit June 24 `13650c8a52e59f945cdcc3fe7fc1b7697c6c810a`

Cloned latest version and :-)

```
Python 3.8.3 (default, May 14 2020, 20:11:43)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from fmm import Network,NetworkGraph,FastMapMatch,FastMapMatchConfig,UBODT
>>> from fmm import UBODTGenAlgorithm
>>> 
```

Imports work :+1: 

Thank you
