### ISSUE TITLE
Error when trying to execute  GPS track / GPS points in CSV file

### ISSUE THREAD

**Issue by rsantosb** [cyang-kth/fmm#253]
I have tried to run the following code (available in example/command_line_example):

GPS trajectory matching in CSV file using fmm:
    # XML configuration
    fmm fmm_config_csv_trajectory.xml
    # Command line arguments
    fmm --ubodt ../data/ubodt.txt --network ../data/edges.shp --gps ../data/trips.csv --k 4 -r 0.4 -e 0.5 --output mr.txt
 
GPS point matching in CSV file using fmm:
    # XML configuration
    fmm fmm_config_csv_point.xml
    # Command line arguments
    fmm --ubodt ../data/ubodt.txt --network ../data/edges.shp --gps ../data/gps.csv --gps_point -k 4 -r 0.4 -e 0.5 --output mr.txt

Also the notebook: stmatch_example.ipynb specifically the part "Match GPS data stored in a file".
(I copied in a file fmm_test_new.py the stmatch_example.ipynb).

I always get the following error:

[2022-11-24 10:55:11.856] [critical] [gps_reader.cpp:137] Id id or Geometry column geom not found
Traceback (most recent call last):
  File "fmm_test_nuevo.py", line 34, in <module>
    status = model.match_gps_file(input_config, result_config, fmm_config)
  File "/usr/lib/python2.7/dist-packages/fmm.py", line 1217, in match_gps_file
    return _fmm.FastMapMatch_match_gps_file(self, gps_config, result_config, config, use_omp)
RuntimeError: Id id or Geometry column geom not found

I followed all the installation steps correctly, without any error.

**Comment by cyang-kth** [comment]
The GPS data format is not corrected identified by the program.

Compare your data with the two files to check the form including field name

- https://github.com/cyang-kth/fmm/blob/master/example/data/gps.csv
- https://github.com/cyang-kth/fmm/blob/master/example/data/trips.csv

**Comment by rsantosb** [comment]
I am trying to run the example files and it fails every time.
What can I do?

**Comment by Blueicei** [comment]
![image](https://github.com/cyang-kth/fmm/assets/49197964/eaca83a6-35d6-46ba-87ba-f81cc2b750f3)

**Comment by zacharyeichen** [comment]
Maybe this should be clarified in the documentation?  
The exact specification of the default csv behavior (id / geometry) mode vs the gps-point mode behavior (id, x, y, time) seems not to be very clearly identified anywhere in the documentation.
