### ISSUE TITLE
Import error when running fmm_test.py

### ISSUE THREAD

**Issue by SwiftPredator** [cyang-kth/fmm#257]
**Note**
Before posting an issue about bug in the program
- Make sure you have downloaded/pulled the **latest version** of repo
- **search the GitHub [issue page](https://github.com/cyang-kth/fmm/issues)** with keywords to check if a similar issue has been posted or not. 

**Describe the bug**
I did a clean install of the fmm library on ubuntu inside a conda environment after some months of not using it. The python versions from installing and executing the test script match. However, i get the following error while importing fmm inside the python bindings:

`
Traceback (most recent call last):
  File "/home/paul/repos/fmm/example/python/fmm_test.py", line 1, in <module>
    from fmm import Network,NetworkGraph,STMATCH,STMATCHConfig
  File "/home/paul/anaconda3/envs/fmm/lib/python3.9/site-packages/fmm.py", line 15, in <module>
    import _fmm
ImportError: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0
`

Maybe some mismatch in a dependent library version?

**Comment by Eric-Liu0526** [comment]
I found a solution that I believe will be helpful to anyone who uses fmm later on. The reason for this bug is that libffi versions are inconsistent. The reference link is https://blog.csdn.net/qq_38606680/article/details/129118491.
