### ISSUE TITLE
errors when "cmake .." for the python extension

### ISSUE THREAD

**Issue by august-zhu** [cyang-kth/fmm#58]
Hi,

I successfully build the c++. But when I tried to install the python extension and run "cmake ..", it gave me errors about SWIG:

```
$ cmake ..
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++.exe
-- Check for working CXX compiler: /usr/bin/c++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found SWIG: /usr/bin/swig.exe (found version "3.0.12")
-- Found GDAL: /usr/lib/libgdal.dll.a (found suitable version "3.0.4", minimum required is "2.2")
-- Found PythonLibs: /usr/lib/libpython2.7.dll.a (found suitable version "2.7.16", minimum required is "2.7")
-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   serialization
CMake Deprecation Warning at /usr/share/cmake-3.14.5/Modules/UseSWIG.cmake:559 (message):
  SWIG_ADD_MODULE is deprecated.  Use SWIG_ADD_LIBRARY instead.
Call Stack (most recent call first):
  CMakeLists.txt:57 (swig_add_module)


CMake Warning (dev) at /usr/share/cmake-3.14.5/Modules/UseSWIG.cmake:600 (message):
  Policy CMP0078 is not set: UseSWIG generates standard target names.  Run
  "cmake --help-policy CMP0078" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

Call Stack (most recent call first):
  /usr/share/cmake-3.14.5/Modules/UseSWIG.cmake:560 (swig_add_library)
  CMakeLists.txt:57 (swig_add_module)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/share/cmake-3.14.5/Modules/UseSWIG.cmake:460 (message):
  Policy CMP0086 is not set: UseSWIG honors SWIG_MODULE_NAME via -module
  flag.  Run "cmake --help-policy CMP0086" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  /usr/share/cmake-3.14.5/Modules/UseSWIG.cmake:695 (SWIG_ADD_SOURCE_TO_MODULE)
  /usr/share/cmake-3.14.5/Modules/UseSWIG.cmake:560 (swig_add_library)
  CMakeLists.txt:57 (swig_add_module)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Creating makefiles for system: CYGWIN-3.1.4(0.340/5/3)
-- Configuring done
-- Generating done
-- Build files have been written to: /cygdrive/d/Google Drive/Research/INRIXData/MD/fmm-master/python/build
```

I checked the ccmake, but did not find any SWIG_ADD_MODULE or SWIG_ADD_LIBRARY tag.

Thanks!

**Comment by cyang-kth** [comment]
@august-zhu 

That is only warning but not error according to the log. You can continue with make to see if the Python can be build successfully. 

I actually encountered every similar warning on my machine. So I will try to remove some of them or suppress them.

**Comment by cyang-kth** [comment]
@august-zhu 

You can run 
```
rm CMakeCache.txt
cmake -Wno-dev ..
```

**Comment by august-zhu** [comment]
@cyang-kth 

Thanks. It worked.

**Comment by august-zhu** [comment]
Hi,

I had another problem - adding the build folder to PYTHONPATH is not working.

I can only import fmm when the current directory is under the build folder (the importing fmm can obviously run under the build folder).
```
august_zhu@DESKTOP-P5KQ2S3 /cygdrive/d/fmm-master/python/build
$ python
Python 2.7.16 (default, Mar 20 2019, 12:15:19)
[GCC 7.4.0] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fmm
>>>
```

I checked the sys.path, and it seems that the build folder is in the PYTHONPATH:
```
$ echo $PYTHONPATH
:/cygdrive/d/fmm-master/python/build
```

But when I tried to import fmm under a different folder, it gives me error:
```
$ python
Python 2.7.16 (default, Mar 20 2019, 12:15:19)
[GCC 7.4.0] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/home/august_zhu', '/cygdrive/d/fmm-master/python/build', '/usr/lib/python27.zip', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-cygwin', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/lib/python2.7/site-packages']
>>> import fmm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cygdrive/d/fmm-master/python/build/fmm.py", line 17, in <module>
    _fmm = swig_import_helper()
  File "/cygdrive/d/fmm-master/python/build/fmm.py", line 16, in swig_import_helper
    return importlib.import_module('_fmm')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No such file or directory
>>> exit()
```

Thanks.

**Comment by cyang-kth** [comment]
@august-zhu 

I am not sure about that problem. 
I do not have a windows computer at hand to test it. It builds successfully on Mac and Ubuntu. 

It seems that you have a cygwin setup, but you install the fmm at some other drive. 
```
/cygdrive/d/fmm-master/python/build
```

Can you try to place it under some folder in the your home directory like this one

```
/home/august_zhu/workspace/fmm-master
```

Also remember to remove the old PYTHONPATH from your `.bashrc` file

```
nano ~/.bashrc
```
Comment out or remove this line 
```
# export PYTHONPATH=${PYTHONPATH}:/cygdrive/d/fmm-master/python/build
```

Remember to run
```
source ~/.bashrc
```
to update the environment variables each time you modify that file.

**Comment by cyang-kth** [comment]
This issue is not active for 7 days, so it is closed.
